config/routes.rb
Rails.application.routes.draw do
  resources :dogs
  root 'dogs#index'
  # get 'dogs/index'
  # get 'dogs/show'
  # get 'dogs/new'
  # get 'dogs/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :current_dog, only: [:show, :edit, :update, :destroy]

  def index
    @dogs = Dog.all
  end

  def show

  end

  def new
    @dog = Dog.new
  end

  def create
    dog = Dog.create(dog_params)

    redirect_to dog_path(dog)
  end

  def edit

  end

  def update
    @dog.update(dog_params)

    redirect_to dog_path(@dog)
  end

  def destroy
    @dog.destroy

    redirect_to dogs_path
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :phrase)
  end

  def current_dog
    @dog = Dog.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/edit.html.erb
<h1>Update Dog</h1>
<%= form_with model: @dog do |form| %>
    <%= form.text_field :name, placeholder: "name" %>
    <%= form.text_field :phrase, placeholder: "phrase" %>
    <%= form.submit %>
<% end %>
<%= link_to 'Back', dogs_path  %>

app/views/dogs/index.html.erb
<h1>Dogs#index</h1>

<table>
    <% @dogs.each do |dog| %>
        <tr>
            <td><%= link_to dog.name, dog_path(dog) %></td>
            <td><%= button_to 'Edit', edit_dog_path(dog), method: 'get'%></td>
            <td><%= button_to 'Remove', dog_path(dog), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </table>
  <%= link_to "Add a New Dog", new_dog_path %>

app/views/dogs/new.html.erb
<h1>Create a Dog</h1>
<%= form_with model: @dog do |form| %>
    <%= form.text_field :name, placeholder: "name" %>
    <%= form.text_field :phrase, placeholder: "phrase" %>
    <%= form.submit %>
<% end %>

<%= link_to 'Back', dogs_path  %>

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>
<p><%= @dog.phrase %></p>

<%= link_to 'Back', dogs_path  %>
<%= link_to 'Edit', edit_dog_path  %>
<%= link_to 'Remove', @dog, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>